openapi: "3.0.0"
info:
  version: 1.0.0
  title: Servicio impuestos
paths:
  /[endpoint del servicio]:
    get:
      summary: Obtiene la información de producto y agrega importe y moneda de los impuestos
      responses:
        '200':
          description: Operación exitosa
