openapi: "3.0.0"
info:
  version: 1.0.0
  title: Servicio impuesto
paths:
  /impuesto/id:
    get:
      summary: Obtiene la información de producto y agrega importe y moneda de impuesto
      responses:
        '200':
          description: Operación exitosa
