apiVersion: apps/v1
kind: Deployment
metadata:
  name: fecha-deployment
  labels:
    app: fecha-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fecha-app
  template:
    metadata:
      labels:
        app: fecha-app
    spec:
      containers:
      - name: fecha-app
        image: edunzz/fecha-app:latest
        ports:
        - containerPort: 4000
---
apiVersion: v1
kind: Service
metadata:
  name: fecha-app-service
spec:
  selector:
    app: fecha-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4000
  type: LoadBalancer
