apiVersion: apps/v1
kind: Deployment
metadata:
  name: compra-deployment
  labels:
    app: compra-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: compra-app
  template:
    metadata:
      labels:
        app: compra-app
    spec:
      containers:
      - name: compra-app
        image: edunzz/k8s_laboratory:compra-cross
        env:
        - name: DT_TENANT
          value: "--DT_TENANT--"
        - name: DT_TOKEN
          value: "--DT_TOKEN--"
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: compra-app-service
spec:
  selector:
    app: compra-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
