apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  labels:
    app: inventario-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventario-app
  template:
    metadata:
      labels:
        app: inventario-app
    spec:
      containers:
      - name: inventario-app
        image: edunzz/otel_demo:inventario-backend
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: inventario-app-service
spec:
  selector:
    app: inventario-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
