apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:5.7
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "password"
        - name: MYSQL_DATABASE
          value: "inventario_db"
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-storage
          mountPath: /var/lib/mysql
        - name: init-db
          mountPath: /docker-entrypoint-initdb.d
      volumes:
      - name: mysql-storage
        persistentVolumeClaim:
          claimName: mysql-pvc
      - name: init-db
        configMap:
          name: init-db
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: init-db
data:
  init.sql: |
    USE inventario_db;
    CREATE TABLE inventario (id INT AUTO_INCREMENT, nombre_producto VARCHAR(255), precio_unidad DECIMAL(10,2), PRIMARY KEY(id));
    INSERT INTO inventario (nombre_producto, precio_unidad) VALUES ('teclado', 150.00);
    INSERT INTO inventario (nombre_producto, precio_unidad) VALUES ('mouse', 50.00);
    INSERT INTO inventario (nombre_producto, precio_unidad) VALUES ('monitor', 500.00);
    INSERT INTO inventario (nombre_producto, precio_unidad) VALUES ('laptop', 1000.00);
    INSERT INTO inventario (nombre_producto, precio_unidad) VALUES ('cpu', 800.00);
    INSERT INTO inventario (nombre_producto, precio_unidad) VALUES ('impresora', 300.00);
    INSERT INTO inventario (nombre_producto, precio_unidad) VALUES ('router', 100.00);
    INSERT INTO inventario (nombre_producto, precio_unidad) VALUES ('webcam', 75.00);
